name: Approve dependabot PR

on:
  workflow_call:
    secrets:
      PAT:
        description: Personal access token
        required: true
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  approve:
    runs-on: ${{ inputs.runs-on }}
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
    - name: Fetch metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
    - name: Auto merge and approve
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.PAT }}
        UPDATE_TYPE: ${{ steps.metadata.outputs.update-type }}
      shell: bash
      run: |
        gh pr merge "$PR_URL" --auto --squash --delete-branch
        if [[ "$UPDATE_TYPE" =~ version-update:(semver-patch|semver-minor) ]]; then
          gh pr review "$PR_URL" --approve
          gh pr comment "$PR_URL" --body "Approved \`$UPDATE_TYPE\`"
        else
          gh pr comment "$PR_URL" --body "Skipping approval because of \`$UPDATE_TYPE\`"
        fi
