name: Onboard repository

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run against
        type: environment
        required: true
      repository:
        description: Repository with owner (i.e. adevinta/vulcan-cicd)
        type: string
        required: true
jobs:
  onboard:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        path: target
        token: ${{ secrets.ONBOARD_TOKEN }}
        github-server-url: https://${{ vars.ONBOARD_GH_HOST }}
    - name: Onboard repository
      env:
        REPOSITORY: ${{ inputs.repository }}
        GH_HOST: ${{ vars.ONBOARD_GH_HOST }}
        PAT: ${{ secrets.ONBOARD_TOKEN }}
        DEPENDABOT_AUTOMERGE_TOKEN: ${{ secrets.AUTOMERGE_TOKEN }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      shell: bash
      run: |
        cd ./target
        if [ "$GH_HOST" == "github.com" ]; then
          export GH_TOKEN=$PAT
        else
          export GH_ENTERPRISE_TOKEN=$PAT
        fi
        $GITHUB_WORKSPACE/scripts/onboard.sh
